apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin-secret
    namespace: gitea
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Dx+jB/7R5inprLY=,iv:tAde4xd6BzwbzygtIsRzVi+qPFOuekotnDjR3j3NQP8=,tag:nM02yRNWdp3PMQ6HNFULyA==,type:str]
    password: ENC[AES256_GCM,data:sE5jSDk9q3aElC7xaCl2wgCNyqll/aOXd4/FFKKjtkpNKYPBkNJA+BcPL6g=,iv:zFQS9NTw57f8bUBvS1YNCxveGntvrPhr1I6JZqBRSB0=,tag:KWpS+r/dXhnu5g99VG8mTw==,type:str]
    email: ENC[AES256_GCM,data:gOrXEc7VOvsAsijNOMEt4Bg07HQQUA==,iv:uFTWChA93Tyzp66odC2U58FxHNirOv+FEWzGmeb5dbs=,tag:IfswgMjQByHfXr4NA1vq/g==,type:str]
sops:
    age:
        - recipient: age1wz30awrey9tp8w8wxcdrccsn57x9ccnz9250u8tv3thc3kr7nqjsqv7m6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTU5USXZxVU8waGNYRkwz
            UlhmL2xpcEtDNEpHT1RsZ21XVlVFTUs1T1NnCjVjOFZNdUJ0WUxxZWNGWjgwRHpO
            ZXo0YVZNMzdBOStUZlVRc3JMZFdmZkkKLS0tIGtTd1JDTjl1eGREcmY2NXQ1NHQ0
            RG1sajdEV3pqUE83SFZVbjlId1BzaHMKQ6tCqPPQMSxcQtP0DZ0B8IIOhchijlX0
            RBglzb97cnIUQos4izVPDBPYgoobSt7pvo6uReOLYQWhA7dlxIhbuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T16:08:38Z"
    mac: ENC[AES256_GCM,data:xBtFVO3oY0My8iFHQVMsPui0MgPCZLaY9oVNaRqgrgR0CY9+Tf0nzNQydk7Ylque2r51tSbDpU502Ia+1XpZnXqacYcX+HqAhWea2HYyJZdu2eAcclgNGeuDReqeGgPUPuscbBQ2jt6Lasj5cU9yPUrrTErhTzL1owh/xRO49xc=,iv:cohqRa5QVoE5UGIgpNoNQDS67j+clPY7WFfu+660tUc=,tag:w5Bdw7kqjXATKWcBD546Bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
