apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 30m
  chart:
    spec:
      chart: gitea
      version: 12.4.x
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
      interval: 12h
  install:
    remediation:
      retries: 3
    createNamespace: false
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    replicaCount: 1

    # Persistence
    persistence:
      enabled: true
      size: 5Gi
      storageClass: longhorn

    # Embedded SQLite (no external DB)
    gitea:
      config:
        database:
          DB_TYPE: sqlite3
          PATH: /data/gitea/gitea.db

        repository:
          ROOT: /data/git/repositories
          DEFAULT_BRANCH: main

        server:
          DOMAIN: gitea.int.centreon.com
          ROOT_URL: https://gitea.int.centreon.com
          HTTP_PORT: 3000
          DISABLE_SSH: false
          SSH_PORT: 22
          START_SSH_SERVER: true
          SSH_LISTEN_PORT: 2222

        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: true

        attachment:
          ENABLED: true
          MAX_SIZE: 10
          MAX_FILES: 5

        lfs:
          ENABLED: false

        admin:
          DISABLE_REGULAR_ORG_CREATION: true

      admin:
        existingSecret: gitea-admin-secret

    # Ingress
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: gitea.int.centreon.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitea.int.centreon.com

    # SSH Service (LoadBalancer for git clone via SSH)
    service:
      ssh:
        type: LoadBalancer
        port: 22
        annotations:
          metallb.universe.tf/allow-shared-ip: gitea-ssh

    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 512Mi
