apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.19.x  # Latest 1.19 patch version (auto-updates for bugfixes)
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  install:
    remediation:
      retries: 3
    createNamespace: false
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    # Full name override
    fullnameOverride: external-dns-pihole

    # Log level
    logLevel: debug  # Change to 'info' after testing

    # Use webhook provider
    provider:
      name: webhook

      # Webhook configuration
      webhook:
        # Use the tarantini-io webhook image for Pi-hole
        image:
          repository: ghcr.io/tarantini-io/external-dns-pihole-webhook
          tag: main

        # Environment variables for the webhook
        env:
          - name: PIHOLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pihole-password
                key: EXTERNAL_DNS_PIHOLE_PASSWORD

          - name: PIHOLE_SERVER
            value: "https://192.168.0.102:8443"

          - name: PIHOLE_TLS_INSECURE
            value: "true"

          - name: LOG_LEVEL
            value: "debug"

        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

    # DNS sync policy
    policy: sync  # Use 'upsert-only' to preserve manual records

    # Data sources
    sources:
      - ingress

    # TXT registry for tracking changes
    txtPrefix: "k8s."
    txtOwnerId: "external-dns-pihole"

    # Domain filtering
    domainFilters:
      - int.centreon.com

    # Ingress class to watch
    ingressClassNames:
      - traefik

    # Service account
    serviceAccount:
      create: true
      name: external-dns-pihole

    # RBAC
    rbac:
      create: true

    # Resource limits
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
