apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: external-dns
type: Opaque
stringData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:ryWVtxk34lY=,iv:xQV0yDwXQ3/EGVtyTBXd9k04Rk9kvxvK/d7qDcpMC+Q=,tag:7/FoEV4n+N3M91DJWJOsxA==,type:str]
sops:
    age:
        - recipient: age1wz30awrey9tp8w8wxcdrccsn57x9ccnz9250u8tv3thc3kr7nqjsqv7m6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhb01Fc093Z21RYW5pZ2lh
            YzBSdU1LNysyOHJ1Z2ZtRnlIdkV3ZC95a2owCnpWNmFJbEo1MnVWMmh2ZytLcGlX
            N1dQR1NTVDlzeDNjb3V0ZzdQbm9YNGsKLS0tIDRzRjcrb0VtWEd1Q0l6NFF6UXJK
            aU1zK0svSEc1L3F6TFpXaHhCUFYycUkKeq54V/DE1hzqUObLYHdn4bMZU8jIrnj1
            KInNOQEk0LMuq6N4LPPMMS5HYz4bJN39Jz5AwGWWPXDUDCF0wJP27Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T17:55:49Z"
    mac: ENC[AES256_GCM,data:W21oyudyTCADHI0xJxN6/AzFAON4K0nkSr1TB8ahtzl/e6jQYzW6RzrXqjq5v95dPZAL19+IGYDoXr5kgYH9w/ReN6sGnuGpUSfQt2Y5cinMlZiGCwGARNwz8htBGsQo6LAzt6FxhnnTClcOY96HLOp1UH/xfo57LcTF2rzm7jM=,iv:wj9hfRDLfMWfKCwg51+MKBRvaZSpuR0urXss9h90pBM=,tag:xaFWE/kxwvAG6oGAjGKS7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
