apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
  namespace: it-tools
spec:
  interval: 30m
  chart:
    spec:
      chart: it-tools
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: jeffresc
        namespace: it-tools
      interval: 12h
  install:
    remediation:
      retries: 3
    createNamespace: false
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    # Replica count
    replicaCount: 2

    # Image configuration
    image:
      repository: corentinth/it-tools
      pullPolicy: IfNotPresent
      tag: ""  # Uses chart's default version

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Ingress configuration
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: ""
      hosts:
        - host: it-tools.int.centreon.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ""  # Uses default wildcard certificate
          hosts:
            - it-tools.int.centreon.com

    # Resource limits
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 128Mi

    # Pod security
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000

    # Container security
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true

    # Health probes
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10

    readinessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5

    # Affinity - spread across nodes
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - it-tools
              topologyKey: kubernetes.io/hostname
